sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creating an image with dockerfile"
  - docker build -t jyj2487/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true jyj2498/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "Docker-react-app-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-980416005937"
  bucket_path: "docker-react-app"
  on:
    branch: main

notifications:
  emails:
    recipients:
      - jyj2487@naver.com
